SecretKey: amVmZmdlZWs=
NormSubStringTitleLength: 100
NormSubStringDescriptionLength: 400
NormSubFullTextLength: 30000
NormSubStringDomainLength: 50
DatabaseURI: mongodb://localhost:27017
Port: 8001
Cache:
  DB: 0
  Password:
  Addr: localhost:6379
App:
  SessionTTL: 2592000
Mq:
  Addr: 192.168.1.137:11300
